name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :protect:build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            protect/build/outputs/aar/protect-release.aar
            cordova-plugin-security-checker/**/*
          generate_release_notes: true
          draft: false
          prerelease: false
